### ISSUE TITLE
Cannot create image from data on these particular files.

### ISSUE THREAD

**Issue by Git-Forked** [Sharpik/Minetest-SharpNet-Photo-Realism-Texturespack#2]
![photo_realism-error](https://user-images.githubusercontent.com/66106762/105627222-80939300-5e03-11eb-9aeb-64a3fd8f5161.png)

Everything else seems to work fine, and thank you for a great texture pack.

**Comment by Sharpik** [comment]
Hi, thanks for cooperation.
I tried to resave this images.
Please let me know, if it help.

(It's too smal update to push it on Content DB so You have to download it from here)

**Comment by Git-Forked** [comment]
![Screenshot_20210126_044652](https://user-images.githubusercontent.com/66106762/105828846-a058c180-5f91-11eb-8326-8368810c91c6.png)

Seems to have fixed all but one now.  Perhaps you skipped over repairing this one, or it's still broken.

**Comment by Git-Forked** [comment]
Any time frame for when this last image might be fixed?  Have been waiting to update my server with it.

**Comment by Sharpik** [comment]
Fixed

**Comment by Git-Forked** [comment]
Thank you.
