### ISSUE TITLE
Spelling Errors

### ISSUE THREAD

**Issue by Git-Forked** [Sharpik/Minetest-SharpNet-Photo-Realism-Texturespack#3]
Some files are spelled improperly: 

forniture_black_metal.jpg     ->     furniture_black_metal.jpg
forniture_marble_base_ducha_top.jpg     ->     furniture_marble_base_?????_top.jpg
forniture_metal.jpg     ->     furniture_metal.jpg

The word 'forniture' in each file should be properly spelled 'furniture'
and no idea what a 'ducha' is, even Google does not know.

**Comment by Sharpik** [comment]
fixed
