### ISSUE TITLE
Mod name does not follow naming conventions

### ISSUE THREAD

**Issue by Git-Forked** [Sharpik/Minetest-SharpNet-Photo-Realism-Texturespack#4]
**2021-03-08 17:22:42: ACTION[Main]: Server: Shutting down
2021-03-08 17:22:43: ERROR[Main]: ModError: Error loading mod "Minetest-SharpNet-Photo-Realism-Texturespack": Mod name does not follow naming conventions: Only characters [a-z0-9_] are allowed.** 

### **Minetest server info:** 
```
Minetest 5.4.0 (Linux)
Using Irrlicht 1.8.4
Using Lua 5.1.5
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
USE_FREETYPE=1
```
Error causes server to shutdown.

**Comment by Sharpik** [comment]
Hi, it's probably becouse texture folder name from this Git (When You install it from Content DB.. It will be OK).
Just rename it in Your Textures folder to: sharpnet_textures and it should work.
