### ISSUE TITLE
Convert JPEG images to PNG

### ISSUE THREAD

**Issue by WulftheNordicRanger** [Sharpik/Minetest-SharpNet-Photo-Realism-Texturespack#5]
Minetest doesn't always play nice with JPEG and in particular the stone texture was having some issues on fever. Converting the file to PNg fixed this

**Comment by Sharpik** [comment]
The question is whether larger (in bytes) textures are worth it and whether it will affect performance on old PCs. I'm tyring to do this textures pack compatible with phones and old PCs.

**Comment by Sharpik** [comment]
Done
